export const skype=[
    { label: 'Asia/Karachi', value: 'Asia/Karachi' },
    { label: 'Asia/Almaty', value: 'Asia/Almaty' },
    { label: 'Asia/Amman', value: 'Asia/Amman' },
    { label: 'Asia/Anadyr', value: 'Asia/Anadyr' },
    { label: 'Asia/Aqtau', value: 'Asia/Aqtau' },
    { label: 'Asia/Aqtobe', value: 'Asia/Aqtobe' },
    { label: 'Asia/Ashgabat', value: 'Asia/Ashgabat' },
    { label: 'Asia/Atyrau', value: 'Asia/Atyrau' },
    { label: 'Asia/Baghdad', value: 'Asia/Baghdad' },
    { label: 'Asia/Baku', value: 'Asia/Baku' },
    { label: 'Asia/Bankok', value: 'Asia/Bankok' },
    { label: 'Asia/Barnaul', value: 'Asia/Barnaul' },
    { label: 'Asia/Beirut', value: 'Asia/Beirut' },
    { label: 'Asia/Bishkek', value: 'Asia/Bishkek' },
    { label: 'Asia/Brunie', value: 'Asia/Brunie' },
    { label: 'Asia/Chita', value: 'Asia/Chita' },
    { label: 'Asia/Choibalsan', value: 'Asia/Choibalsan' },
    { label: 'Asia/Colombo', value: 'Asia/Colombo' },
    { label: 'Asia/Damascus', value: 'Asia/Damascus' },
    { label: 'Asia/Dhaka', value: 'Asia/Dhaka' },
    { label: 'Asia/Dili', value: 'Asia/Dili' },
    { label: 'Asia/Dubai', value: 'Asia/Dubai' },
    { label: 'Asia/Dushanbe', value: 'Asia/Dushanbe' },
    { label: 'Asia/Famagusta', value: 'Asia/Famagusta' },
    { label: 'Asia/Ghaza', value: 'Asia/Ghaza' },
    { label: 'Asia/Herbon', value: 'Asia/Herbon' },
    { label: 'Asia/Ho_Chi_Minh', value: 'Asia/Ho_Chi_Minh' },
    { label: 'Asia/Hong_Kong', value: 'Asia/Hong_Kong' },
    { label: 'Asia/Hovd', value: 'Asia/Hovd' },
    { label: 'Asia/Irkutsk', value: 'Asia/Irkutsk' },
    { label: 'Asia/Jakarta', value: 'Asia/Jakarta' },
    { label: 'Asia/Jayapura', value: 'Asia/Jayapura' },
    { label: 'Asia/Kabul', value: 'Asia/Kabul' },
    { label: 'Asia/Kolkata', value: 'Asia/Kolkata' },
   { label: 'Africa/Abidjan', value: 'Africa/Abidjan' },
    { label: 'Africa/Accra', value: 'Africa/Accra' },
    { label: 'Africa/Algiers', value: 'Africa/Algiers' },
    { label: 'Africa/Bissau', value: 'Africa/Bissau' },
    { label: 'Africa/Cairo', value: 'Africa/Cairo' },
    { label: 'Africa/Casablanca', value: 'Africa/Casablanca' },
    { label: 'Africa/Ceuta', value: 'Africa/Ceuta' },
    { label: 'Africa/El_Aaiun', value: 'Africa/El_Aaiun' },
    { label: 'Africa/Johannesburg', value: 'Africa/Johannesburg' },
    { label: 'Africa/Juba', value: 'Africa/Juba' },
    { label: 'Africa/Khartoum', value: 'Africa/Khartoum' },
    { label: 'Africa/Lagos', value: 'Africa/Lagos' },
    { label: 'Africa/Maputo', value: 'Africa/Maputo' },
    { label: 'Africa/Monrovia', value: 'Africa/Monrovia' },
    { label: 'Africa/Nairobi', value: 'Africa/Nairobi' },
    { label: 'Africa/Ndjamena', value: 'Africa/Ndjamena' },
    { label: 'Africa/Tripoli', value: 'Africa/Tripoli' },
    { label: 'Africa/Tunis', value: 'Africa/Tunis' },
    { label: 'Africa/Windhoek', value: 'Africa/Windhoek' },

    { label: 'America/Lima', value: 'America/Lima' },
    { label: 'America/La_Paz', value: 'America/La_Paz' },
    { label: 'America/Los_Angeles', value: 'America/Los_Angeles' },
    { label: 'America/Maceio', value: 'America/Maceio' },
    { label: 'America/Managua', value: 'America/Managua' },
    { label: 'America/Manaus', value: 'America/Manaus' },
    { label: 'America/Martinique', value: 'America/Martinique' },
    { label: 'America/Matamoros', value: 'America/Matamoros' },
    { label: 'America/Mazatlan', value: 'America/Mazatlan' },

    { label: 'Antarctica/Casey', value: 'Antarctica/Casey' },
    { label: 'Antarctica/Davis', value: 'Antarctica/Davis' },
    { label: 'Antarctica/DumontDUrville', value: 'Antarctica/DumontDUrville' },
    { label: 'Antarctica/Macquarie', value: 'Antarctica/Macquarie' },
    { label: 'Antarctica/Mawson', value: 'Antarctica/Mawson' },
    { label: 'Antarctica/Palmer', value: 'Antarctica/Palmer' },
    { label: 'Antarctica/Rothera', value: 'Antarctica/Rothera' },
    { label: 'Antarctica/Ryowa', value: 'Antarctica/Ryowa' },
    { label: 'Antarctica/Troll', value: 'Antarctica/Troll' },

    { label: 'Atlantic/Stanley', value: 'Atlantic/Stanley' },
    { label: 'Atlantic/Adelaide', value: 'Atlantic/Adelaide' },
    { label: 'Atlantic/Brisbane', value: 'Atlantic/Brisbane' },
    { label: 'Atlantic/Broken_Hill', value: 'Atlantic/Broken_Hill' },
    { label: 'Atlantic/Currie', value: 'Atlantic/Currie' },
    { label: 'Atlantic/Darwin', value: 'Atlantic/Darwin' },
    { label: 'Atlantic/Eucla', value: 'Atlantic/Eucla' },
    { label: 'Atlantic/Hobard', value: 'Atlantic/Hobard' },
    { label: 'Atlantic/Lindeman', value: 'Atlantic/Lindeman' },
   




]